### PR TITLE
Update pangolin v4

### PR DESCRIPTION
**Pull request by talnor**
### The purpose of the code changes are as follows:
* I did a thing

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [x] Produced files contain expected values
- [x] The code has been reviewed by @octocat

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by talnor** [comment]
Fixes issue https://github.com/genomic-medicine-sweden/gms-artic/issues/52

**Comment by sofstam** [comment]
Tests for this PR for Stockholm region (CG)

```
source activate D_mutant

mutant analyse sarscov2 /home/proj/development/mutant/cases/maturejay/fastq/ --config_artic /home/proj/development/mutant/configs/artic-dev.json --config_case /home/proj/development/mutant/cases/maturejay/case_config.json --outdir /home/proj/development/mutant/cases/maturejay/results/ --profiles slurm,singularity
```

Results:

```
bcftools,1.10.2
bwa,0.7.17-r1188
constellations,0.1.4
fastqc,0.11.9
freebayes,1.3.5
gofasta,1.0.0
ivar,1.3.1
multiqc,1.11
nextclade,1.10.2
pangolin-data,1.2.133
pangolin,4.0.2
picard,2.25.2
python,3.8.12
samtools,1.10
scorpio,0.3.16
snakemake,6.4.1
trim_galore,0.6.4_dev
usher,v0.5.3
```

**Comment by sofstam** [comment]
Tests for this PR for Stockholm region (CG)

```
source activate D_mutant

mutant analyse sarscov2 /home/proj/development/mutant/cases/maturejay/fastq/ --config_artic /home/proj/development/mutant/configs/artic-dev.json --config_case /home/proj/development/mutant/cases/maturejay/case_config.json --outdir /home/proj/development/mutant/cases/maturejay/results/ --profiles slurm,singularity
```

Results:

```
bcftools,1.10.2
bwa,0.7.17-r1188
constellations,0.1.4
fastqc,0.11.9
freebayes,1.3.5
gofasta,1.0.0
ivar,1.3.1
multiqc,1.11
nextclade,1.10.2
pangolin-data,1.2.133
pangolin,4.0.2
picard,2.25.2
python,3.8.12
samtools,1.10
scorpio,0.3.16
snakemake,6.4.1
trim_galore,0.6.4_dev
usher,v0.5.3
```

**Review by sofstam — APPROVED** [review]
The tests passed. Looks good to me.

**Pull request merged**
