### PR TITLE
Update pangolin container

### PR DESCRIPTION
**Pull request by sofstam**
### The purpose of the code changes are as follows:
* Update the pangolin container to the latest version so that nanopore analysis can be used in production in CG Stockholm

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [x] The code has been reviewed by @henningonsbring 

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by henningonsbring — APPROVED** [review]
👍

**Comment by henningonsbring** [comment]
@sofstam please run black on everything before merge

**Review by JD2112 — APPROVED** [review]
Hej @sofstam Nicely done!! I think PR #60 is same like this. Would you please merge both when you have time. Please consider rebase because #62 already been merged :)

**Comment by sofstam** [comment]
@JD2112 I do not see any conflicts with the base branch, I was thinking of merging.

**Pull request merged**
