### PR TITLE
Fix GitHub workflow docker builds

### PR DESCRIPTION
**Pull request by talnor**
### The purpose of the code changes are as follows:
* Fix GitHub workflow for docker builds https://github.com/genomic-medicine-sweden/gms-artic/issues/79
  * This changes the docker builds for the _Illumina_ and _Nanopore_ from running on push to master + cron schedule to only run on push to master. Since pangolin is in a separate container, the cron updates are not necessary for these.  
* Add workflows for stage builds on push.

#### Will not do
* Fix other workflows that are failing - these are adressed in a separate PR https://github.com/genomic-medicine-sweden/gms-artic/pull/74
* Change the structure for the pangolin docker builds (Would be good to fix in this issue https://github.com/genomic-medicine-sweden/gms-artic/issues/81)

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [ ] The code has been reviewed by @octocat
- [x] The stage images are built and uploaded successfully

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by sylvinite — CHANGES_REQUESTED** [review]
Looks really good. Some structural feedback:
* Two of the self-tests are currently failing
* The building images recipes are better suited in another folder than workflow, which is currently just for the pipeline's subworkflows
* Both the push recipes look identical. It could also be clearer in the difference of what the regular recipes and the push recipe does.

**Comment by talnor** [comment]
> Looks really good. Some structural feedback:
> 
> * Two of the self-tests are currently failing
Indeed! They have been for some time as well. I will try to fix it in another PR.

> * The building images recipes are better suited in another folder than workflow, which is currently just for the pipeline's subworkflows

I am not sure if GitHub actions will pick them up if we move them elsewhere.

> * Both the push recipes look identical. It could also be clearer in the difference of what the regular recipes and the push recipe does.

True! For each build-file, I made one file for the master branch and one to be used for testing in PRs. Perhaps renaming the files makes it more clear?
 
{build_dockerfile}_on_push.yml -> {build_dockerfile}_master.yml
{build_dockerfile}_on_push_stage.yml -> {build_dockerfile}_stage.yml

**Review by sylvinite — APPROVED** [review]

**Comment by sylvinite** [comment]
All the suggestions sounds good to me. Ill unlock the PR.

**Review by rannick — APPROVED** [review]
LGTM!

**Pull request merged**
