### PR TITLE
Run versions process with nanopore medaka workflow

### PR DESCRIPTION
**Pull request by henningonsbring**
### The purpose of the code changes are as follows:
* I added so versions process is running with medaka
* Blacked the whole project to get consistent formatting of the code

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [ ] The code has been reviewed by @octocat

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by henningonsbring** [comment]
Let me know what you think about me running black on the code @JD2112, if you do not like it I can do a new PR with only adding the version process to the medaka workflow.

**Comment by henningonsbring** [comment]
After testing the code here is the content of the `versions.csv` file:
```
artic,1.1.3
bwa,0.7.17-r1188
constellations,0.1.10
gofasta,0.0.4
mafft,7.505
medaka,1.0.3
minimap2,2.17-r941
muscle,v3.8.1551
nanopolish,0.13.2
nextclade,1.10.2
pangolin-data,1.12
pangolin,4.1.2
porechop,0.3.2pre
python,3.6.15
samtools,1.10
scorpio,0.3.17
snakemake,5.13.0
```

**Comment by JD2112** [comment]
@henningonsbring fine for me. Nice you checked this out.

**Review by JD2112 — APPROVED** [review]
Please merge when you have time.

**Pull request merged**
