### PR TITLE
Include all python3 versions

### PR DESCRIPTION
**Pull request by sofstam**
### The purpose of the code changes are as follows:
* I updated the black test to include all versions of python3

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [ ] The code has been reviewed by @octocat

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by JD2112** [comment]
@sofstam Nice! Is it working good?

**Review by JD2112 — APPROVED** [review]
If it working fine, merge it whenever you've time.

**Comment by sofstam** [comment]
I still get issues, I converted it to draft.

**Comment by sofstam** [comment]
I had to change my local conda environment so that the tests would pass. I will close this PR.

**Pull request closed without merging**
