### PR TITLE
Primer scheme

### PR DESCRIPTION
**Pull request by JD2112**
### The purpose of the code changes are as follows:
* I did a thing

### Standard test procedure
- [X] The self-test mentioned in the README finished successfully
- [X] Produced files contain expected values
- [X] The code has been reviewed by @sylvinite 

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by sylvinite** [comment]
Looks good. New primer scheme. Renaming to use gms repo. And a minor fix to suggest usage of --scheme option.
Rest is just new reference files.

**Review by sylvinite — APPROVED** [review]

**Comment by sofstam** [comment]
Before merging, is it ok if we keep the version of nextclade that we are using now, 1.8.1? Or is it a specific reason for updating to 1.10?

**Comment by JD2112** [comment]
> Before merging, is it ok if we keep the version of nextclade that we are using now, 1.8.1? Or is it a specific reason for updating to 1.10?

There are some bugs fixed with Nextclade v1.10 from the v1.8, so I added this one. https://github.com/nextstrain/nextclade/releases
Of course, I can revert to v1.8.

**Comment by JD2112** [comment]
@sofstam the GHaction script for nanopore requires --scheme to run the pipeline. Could you please add this to the script?

**Pull request merged**
