### PR TITLE
Rich set to fixed version

### PR DESCRIPTION
**Pull request by sofstam**
### The purpose of the code changes are as follows:
*The production team in CG Stockholm got the following error during an analysis:

```
(cg_env) vincent.janvid@vincentjambp cg % docker run -it --entrypoint /bin/bash genomicmedicinesweden/gms-artic-nanopore:latest                                     
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@9a4104a14cf4:/# multiqc --version
Traceback (most recent call last):
  File "/opt/conda/envs/artic/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/opt/conda/envs/artic/lib/python3.6/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/opt/conda/envs/artic/lib/python3.6/site-packages/multiqc/multiqc.py", line 29, in <module>
    from rich.syntax import Syntax
  File "/opt/conda/envs/artic/lib/python3.6/site-packages/rich/syntax.py", line 46, in <module>
    from .console import Console, ConsoleOptions, JustifyMethod, RenderResult
  File "/opt/conda/envs/artic/lib/python3.6/site-packages/rich/console.py", line 36, in <module>
    from rich._null_file import NULL_FILE
  File "/opt/conda/envs/artic/lib/python3.6/site-packages/rich/_null_file.py", line 69, in <module>
    NULL_FILE = NullFile()
  File "/opt/conda/envs/artic/lib/python3.6/typing.py", line 1231, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/opt/conda/envs/artic/lib/python3.6/typing.py", line 1188, in _generic_new
    return base_cls.__new__(cls, *args, **kwds)
TypeError: Can't instantiate abstract class NullFile with abstract methods closed, mode, name

```
* The python library [Rich](https://anaconda.org/conda-forge/rich) got updated to 13.0.1 and this update caused the issue. A quick fix would be to set python rich library to `12.6.0`

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [ ] The code has been reviewed by @Vince-janv 

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by Vince-janv — APPROVED** [review]
Nice, the test case run at CG worked with the new image 👍  It seems like one of the automatic tests is failing in the PR. Is this normal?

**Comment by sofstam** [comment]
Thanks for the review. Yes, one of the automatic tests is expected to fail, right @JD2112?

**Comment by JD2112** [comment]
Yes, right. It's due to the Nextclade update. @sofstam Do you have any updates about the nextclade update integration?

**Review by JD2112 — APPROVED** [review]

**Comment by sofstam** [comment]
We are testing actually now :) @JD2112 
I am merging this PR in the meanwhile.

**Pull request merged**
