### PR TITLE
Update nextclade

### PR DESCRIPTION
**Pull request by sofstam**
### The purpose of the code changes are as follows:
* This PR updates the nextclade version to 2.11
* Also updated to dsl2 https://github.com/genomic-medicine-sweden/gms-artic/issues/66
* Some GitHub actions errors for the PR test workflow fixed (some still remaining)

Note: 
The nanopore docker image in master does not work. Fix in separate PR. 

### Standard test procedure
- [x] The self-test mentioned in the README finished successfully
- [x] Produced files contain expected values
  - [x] For illumina - Yes
  - [x] For nanopore - with container version 2023-06-21-p-4.3-d-1.20-c-0.1.11-s-0.3.17 - Yes
- [x] The code has been reviewed by @octocat

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Review by karlnyr — COMMENTED** [review]
I think all we need now is to format it with `black`

**Comment by sofstam** [comment]
Thanks @karlnyr. I do not know why black does not work. I was thinking if the python version in the tests do not match the python version in my conda environment.I will look into this tomorrow.

**Comment by karlnyr** [comment]
Can you not just run black locally on the following files which seems to fail?

```Command
Identified `/home/runner/work/gms-artic/gms-artic` as project root containing a .git directory.
Sources to be formatted: "."
/home/runner/work/gms-artic/gms-artic/.github/data/nanopore/20200311_142[7](https://github.com/genomic-medicine-sweden/gms-artic/actions/runs/4142762909/jobs/7163816675#step:5:8)_X4_FAK72[8](https://github.com/genomic-medicine-sweden/gms-artic/actions/runs/4142762909/jobs/7163816675#step:5:9)34_a3787181/fast5_pass/FAK72834_pass_barcode07_2[9](https://github.com/genomic-medicine-sweden/gms-artic/actions/runs/4142762909/jobs/7163816675#step:5:10)8b7829_0.fast5 ignored: is a symbolic link that points outside /home/runner/work/gms-artic/gms-artic/.github/data/nanopore/20200311_1427_X4_FAK72834_a3787181
/home/runner/work/gms-artic/gms-artic/.github/data/nanopore/20200311_1427_X4_FAK72834_a3787181/fastq_pass/FAK72834_pass_barcode07_298b7829_0.fastq ignored: is a symbolic link that points outside /home/runner/work/gms-artic/gms-artic/.github/data/nanopore/20200311_1427_X4_FAK72834_a3787181
/home/runner/work/gms-artic/gms-artic/.git ignored: matches the --exclude regular expression
/home/runner/work/gms-artic/gms-artic/bin/makeReport.py already well formatted, good job.
/home/runner/work/gms-artic/gms-artic/bin/get_versions.py already well formatted, good job.
would reformat /home/runner/work/gms-artic/gms-artic/bin/qc.py
would reformat /home/runner/work/gms-artic/gms-artic/bin/process_gvcf.py
would reformat /home/runner/work/gms-artic/gms-artic/bin/type_vcf.py
```

**Comment by sofstam** [comment]
I have already tested it but the tests still fail. I will try now again.

**Comment by karlnyr** [comment]
Oh... Well then I understand your confusion - I hope the version matching works!

**Review by JD2112 — APPROVED** [review]

**Comment by sofstam** [comment]
The black test is now passing. The nanopore tests are supposed to fail. Just let me know when I can merge @karlnyr

**Review by JD2112 — APPROVED** [review]

**Pull request merged**
