### PR TITLE
Update nextclade

### PR DESCRIPTION
**Pull request by sofstam**
### The purpose of the code changes are as follows:
* I updated the nextclade version and this PR closes [#68 ](https://github.com/genomic-medicine-sweden/gms-artic/issues/68). I built the dockers in my own dockerhub account. 

### Standard test procedure
- [ ] The self-test mentioned in the README finished successfully
- [ ] Produced files contain expected values
- [ ] The code has been reviewed by @octocat

### This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by sofstam** [comment]
@JD2112 Could you maybe test that this works locally for you? Or anyone else that could help us with that?
@pbiology The containers in cg are updated every Friday at 04.00 and we need to sync with prod-bioinfo before this PR is merged.

**Comment by JD2112** [comment]
> @JD2112 Could you maybe test that this works locally for you? Or anyone else that could help us with that? @pbiology The containers in cg are updated every Friday at 04.00 and we need to sync with prod-bioinfo before this PR is merged.

@sofstam Can't test locally. "access to the resource is denied".
`Caused by:
  Failed to pull singularity image
  command: singularity pull  --name sofsta-gms-artic-pangolin-latest.img.pulling.1666286780351 docker://sofsta/gms-artic-pangolin:latest > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://sofsta/gms-artic-pangolin:latest: reading manifest latest in docker.io/sofsta/gms-artic-pangolin: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required
`

**Comment by sofstam** [comment]
@JD2112 Thank you! Shall I maybe build the container under `genomicmedicinesweden` and when the PR is tested locally, re-run the default github actions?

**Comment by JD2112** [comment]
@sofstam Sure...or just change the ownership of your Docker container :)

**Comment by JD2112** [comment]
new nextclade cli:

**Comment by JD2112** [comment]
@sofstam #70 
new nextclade cli: 'typing.nf' 
`nextclade run \
        --input-dataset data/sars-cov-2 \
        --output-tree ${sampleName}_tree.json \
        --output-tsv ${sampleName}.tsv \
        --output-json ${sampleName}.json \
        ${consensus_fasta}`

**Review by JD2112 — APPROVED** [review]

**Comment by sofstam** [comment]
@pbiology This PR is ready for merging.

**Comment by pbiology** [comment]
As soon as the checks are resolved I'd go for it

**Pull request merged**
